<?php
$conf_enablepassword="";
$conf_password="d41d8cd98f00b204e9800998ecf8427e";
$conf_masteraddress="192.168.1.1";
$conf_masterssid="Arietta";
$conf_masterchannel="2";
$conf_enablerouter="on";
$conf_routerhostname="Arietta";
$conf_routerssid="Alice-63537521";
$conf_routersecuritytype="wpa";
$conf_routersecuritykey="1vst5m09ahuehl5538dgb0ik";
$conf_routerconfig="dhcp";
$conf_routerip="";
$conf_routermask="";
$conf_routergateway="";
$conf_routerdnsmanual="";
$conf_routerdns="";
$conf_routerdns1="";
?>
