<?php
$conf_enablepassword="";
$conf_password="";
$conf_masteraddress="192.168.1.1";
$conf_masterssid="Arietta";
$conf_masterchannel="2";
$conf_enablerouter="";
$conf_routerhostname="Arietta";
$conf_routerssid="";
$conf_routersecuritytype="";
$conf_routersecuritykey="";
$conf_routerconfig="";
$conf_routerip="";
$conf_routermask="";
$conf_routergateway="";
$conf_routerdnsmanual="";
$conf_routerdns="";
$conf_routerdns1="";
?>
